apiVersion: compute.functionmesh.io/v1alpha1
kind: Function
metadata:
  name: order-validation-function
  namespace: default
spec:
  image: polyzos/food-delivery
  className: sn.academy.food_delivery.services.validation.OrderValidationService
  forwardSourceMessageProperty: true
  MaxPendingAsyncRequests: 1000
  replicas: 1
  maxReplicas: 2
  logTopic: persistent://public/default/order-validation-logs
  input:
    topics:
      - "persistent://orders/inbound/food-orders"
    sinkSchemaType: "avro"
    typeClassName: sn.academy.food_delivery.models.avro.FoodOrder
  resources:
    limits:
      cpu: "0.2"
      memory: 1.1G
    requests:
      cpu: "0.1"
      memory: 1G
  pulsar:
    pulsarConfig: "food-order-validation-config"
  java:
    jar: microservices-webinars-0.0.1.jar
    jarLocation: ""
  clusterName: localpulsar
  autoAck: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: food-order-validation-config
data:
  webServiceURL: http://localpulsar-broker.pulsar.svc.cluster.local:8080
  brokerServiceURL: pulsar://localpulsar-broker.pulsar.svc.cluster.local:6650
