apiVersion: compute.functionmesh.io/v1alpha1
kind: FunctionMesh
metadata:
  name: food-delivery-functionmesh
spec:
  sources:
    - name: orders-source
      image: polyzos/food-delivery
      className: sn.academy.food_delivery.source.FoodOrderSource
      forwardSourceMessageProperty: true
      maxPendingAsyncRequests: 1000
      replicas: 1
      logTopic: persistent://public/default/food-orders-logs
      output:
        producerConf:
          maxPendingMessages: 1000
          maxPendingMessagesAcrossPartitions: 50000
          useThreadLocalProducers: true
        topic: persistent://orders/inbound/food-orders
        sinkSchemaType: "avro"
        typeClassName: sn.academy.food_delivery.models.avro.FoodOrder
      resources:
        limits:
          cpu: "0.2"
          memory: 1.1G
        requests:
          cpu: "0.1"
          memory: 1G
      pulsar:
        pulsarConfig: "food-delivery-mesh-config"
        authSecret: "food-delivery-mesh-secret"
      java:
        jar: microservices-webinars-0.0.1.jar
        jarLocation: ""
      clusterName: pulsar
      autoAck: true

  functions:
    - name: "validation"
      image: polyzos/food-delivery
      className: sn.academy.food_delivery.services.validation.OrderValidationService
      forwardSourceMessageProperty: true
      maxPendingAsyncRequests: 1000
      replicas: 1
      logTopic: persistent://public/default/order-validation-logs
      input:
        topics:
          - "persistent://orders/inbound/food-orders"
        sinkSchemaType: "avro"
        typeClassName: sn.academy.food_delivery.models.avro.FoodOrder
        sourceSpecs:
          "persistent://orders/inbound/food-orders":
            schemaType: "avro"
      resources:
        limits:
          cpu: "0.5"
          memory: 1.1G
        requests:
          cpu: "0.1"
          memory: 1G
      pulsar:
        pulsarConfig: "food-delivery-mesh-config"
        authSecret: "food-delivery-mesh-secret"
      java:
        jar: microservices-webinars-0.0.1.jar
        jarLocation: ""
      clusterName: pulsar
      autoAck: true


    - name: aggregation
      image: polyzos/food-delivery
      className: sn.academy.food_delivery.services.aggregation.OrderAggregationService
      forwardSourceMessageProperty: true
      maxPendingAsyncRequests: 1000
      replicas: 1
      maxReplicas: 3
      logTopic: persistent://public/default/order-aggregation-logs
      input:
        topics:
          - "persistent://orders/validation/aggregated-orders"
        sinkSchemaType: "avro"
        typeClassName: sn.academy.food_delivery.models.avro.ValidatedFoodOrder
        sourceSpecs:
          "persistent://orders/validation/aggregated-orders":
            schemaType: "avro"
      resources:
        limits:
          cpu: "0.6"
          memory: 1.1G
        requests:
          cpu: "0.3"
          memory: 1G
      pulsar:
        pulsarConfig: "food-delivery-mesh-config"
        authSecret: "food-delivery-mesh-secret"
      java:
        jar: microservices-webinars-0.0.1.jar
        jarLocation: ""
      clusterName: pulsar
      autoAck: true

    - name: "geo"
      image: polyzos/food-delivery
      className: sn.academy.food_delivery.services.processing.GeoEncoderService
      forwardSourceMessageProperty: true
      maxPendingAsyncRequests: 1000
      replicas: 1
      logTopic: persistent://public/default/geo-encoding-logs
      input:
        topics:
          - "persistent://orders/validation/geo-encoder"
        sinkSchemaType: "avro"
        typeClassName: sn.academy.food_delivery.models.avro.Address
        sourceSpecs:
          "persistent://orders/validation/geo-encoder":
            schemaType: "avro"
      resources:
        limits:
          cpu: "0.2"
          memory: 1.1G
        requests:
          cpu: "0.1"
          memory: 1G
      pulsar:
        pulsarConfig: "food-delivery-mesh-config"
        authSecret: "food-delivery-mesh-secret"
      java:
        jar: microservices-webinars-0.0.1.jar
        jarLocation: ""
      clusterName: pulsar
      autoAck: true

    - name: "payments"
      image: polyzos/food-delivery
      className: sn.academy.food_delivery.services.processing.PaymentService
      forwardSourceMessageProperty: true
      maxPendingAsyncRequests: 1000
      replicas: 1
      logTopic: persistent://public/default/payments-logs
      input:
        topics:
          - "persistent://orders/validation/payments"
        sinkSchemaType: "avro"
        typeClassName: sn.academy.food_delivery.models.avro.Payment
        sourceSpecs:
          "persistent://orders/validation/payments":
            schemaType: "avro"
      resources:
        limits:
          cpu: "0.2"
          memory: 1.1G
        requests:
          cpu: "0.1"
          memory: 1G
      pulsar:
        pulsarConfig: "food-delivery-mesh-config"
        authSecret: "food-delivery-mesh-secret"
      java:
        jar: microservices-webinars-0.0.1.jar
        jarLocation: ""
      clusterName: pulsar
      autoAck: true

    - name: "restaurants"
      image: polyzos/food-delivery
      className: sn.academy.food_delivery.services.processing.RestaurantCommunicationService
      forwardSourceMessageProperty: true
      maxPendingAsyncRequests: 1000
      replicas: 1
      logTopic: persistent://public/default/restaurant-communication-logs
      input:
        topics:
          - "persistent://orders/validation/restaurants"
        sinkSchemaType: "avro"
        typeClassName: sn.academy.food_delivery.models.avro.FoodOrder
        sourceSpecs:
          "persistent://orders/validation/restaurants":
            schemaType: "avro"
      resources:
        limits:
          cpu: "0.2"
          memory: 1.1G
        requests:
          cpu: "0.1"
          memory: 1G
      pulsar:
        pulsarConfig: "food-delivery-mesh-config"
        authSecret: "food-delivery-mesh-secret"
      java:
        jar: microservices-webinars-0.0.1.jar
        jarLocation: ""
      clusterName: pulsar
      autoAck: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: food-delivery-mesh-config
data:
  webServiceURL: http://pulsar-broker.workshop.svc.cluster.local:8080
  brokerServiceURL: pulsar://pulsar-broker.workshop.svc.cluster.local:6650
  stateStorageServiceUrl: bk://pulsar-bookie.workshop.svc.cluster.local:4181
---
apiVersion: v1
kind: Secret
metadata:
  name: food-delivery-mesh-secret
stringData:
  clientAuthenticationPlugin: "org.apache.pulsar.client.impl.auth.AuthenticationToken"
  clientAuthenticationParameters: ""