apiVersion: compute.functionmesh.io/v1alpha1
kind: FunctionMesh
metadata:
  name: food-delivery-functionmesh
spec:
  sources:
    - name: orders-source
      image: polyzos/food-delivery
      className: sn.academy.food_delivery.source.FoodOrderSource
      forwardSourceMessageProperty: true
      MaxPendingAsyncRequests: 1000
      replicas: 1
      maxReplicas: 3
      logTopic: persistent://public/default/food-orders-logs
      output:
        producerConf:
          maxPendingMessages: 1000
          maxPendingMessagesAcrossPartitions: 50000
          useThreadLocalProducers: true
        topic: persistent://orders/inbound/food-orders
        sinkSchemaType: "avro"
        typeClassName: sn.academy.food_delivery.models.avro.FoodOrder
      resources:
        limits:
          cpu: "0.2"
          memory: 1.1G
        requests:
          cpu: "0.1"
          memory: 1G
      pulsar:
        pulsarConfig: "food-delivery-mesh-config"
      java:
        jar: microservices-webinars-0.0.1.jar
        jarLocation: ""
      clusterName: localpulsar
      autoAck: true

  functions:
    - name: "validation-service"
      image: polyzos/food-delivery
      className: sn.academy.food_delivery.services.validation.OrderValidationService
      forwardSourceMessageProperty: true
      MaxPendingAsyncRequests: 1000
      replicas: 1
      maxReplicas: 5
      logTopic: persistent://public/default/order-validation-logs
      input:
        topics:
          - "persistent://orders/inbound/food-orders"
        sinkSchemaType: "avro"
        typeClassName: sn.academy.food_delivery.models.avro.FoodOrder
      resources:
        limits:
          cpu: "0.2"
          memory: 1.1G
        requests:
          cpu: "0.1"
          memory: 1G
      pulsar:
        pulsarConfig: "food-delivery-mesh-config"
      java:
        jar: microservices-webinars-0.0.1.jar
        jarLocation: ""
      clusterName: localpulsar
      autoAck: true

    - name: aggregation-service
      image: polyzos/food-delivery
      className: sn.academy.food_delivery.services.aggregation.OrderAggregationService
      forwardSourceMessageProperty: true
      MaxPendingAsyncRequests: 1000
      replicas: 1
      maxReplicas: 3
      logTopic: persistent://public/default/order-aggregation-logs
      input:
        topics:
          - "persistent://orders/inbound/aggregated-orders"
        sinkSchemaType: "avro"
        typeClassName: sn.academy.food_delivery.models.avro.ValidatedFoodOrder
      resources:
        limits:
          cpu: "0.2"
          memory: 1.1G
        requests:
          cpu: "0.1"
          memory: 1G
      pulsar:
        pulsarConfig: "food-delivery-mesh-config"
      java:
        jar: microservices-webinars-0.0.1.jar
        jarLocation: ""
      clusterName: localpulsar
      autoAck: true

    - name: "geo-encoding-service"
      image: polyzos/food-delivery
      className: sn.academy.food_delivery.services.processing.GeoEncoderService
      forwardSourceMessageProperty: true
      MaxPendingAsyncRequests: 1000
      replicas: 1
      maxReplicas: 3
      logTopic: persistent://public/default/geo-encoding-logs
      input:
        topics:
          - "persistent://orders/inbound/geo-encoder"
        sinkSchemaType: "avro"
        typeClassName: sn.academy.food_delivery.models.avro.Address
      resources:
        limits:
          cpu: "0.2"
          memory: 1.1G
        requests:
          cpu: "0.1"
          memory: 1G
      pulsar:
        pulsarConfig: "food-delivery-mesh-config"
      java:
        jar: microservices-webinars-0.0.1.jar
        jarLocation: ""
      clusterName: localpulsar
      autoAck: true

    - name: "payments-service"
      image: polyzos/food-delivery
      className: sn.academy.food_delivery.services.processing.PaymentService
      forwardSourceMessageProperty: true
      MaxPendingAsyncRequests: 1000
      replicas: 1
      maxReplicas: 5
      logTopic: persistent://public/default/payments-logs
      input:
        topics:
          - "persistent://orders/inbound/payments"
        sinkSchemaType: "avro"
        typeClassName: sn.academy.food_delivery.models.avro.Payment
      resources:
        limits:
          cpu: "0.2"
          memory: 1.1G
        requests:
          cpu: "0.1"
          memory: 1G
      pulsar:
        pulsarConfig: "food-delivery-mesh-config"
      java:
        jar: microservices-webinars-0.0.1.jar
        jarLocation: ""
      clusterName: localpulsar
      autoAck: true

    - name: "restaurants-service"
      image: polyzos/food-delivery
      className: sn.academy.food_delivery.services.processing.RestaurantCommunicationService
      forwardSourceMessageProperty: true
      MaxPendingAsyncRequests: 1000
      replicas: 1
      maxReplicas: 5
      logTopic: persistent://public/default/restaurant-communication-logs
      input:
        topics:
          - "persistent://orders/inbound/restaurants"
        sinkSchemaType: "avro"
        typeClassName: sn.academy.food_delivery.models.avro.FoodOrder
      resources:
        limits:
          cpu: "0.2"
          memory: 1.1G
        requests:
          cpu: "0.1"
          memory: 1G
      pulsar:
        pulsarConfig: "food-delivery-mesh-config"
      java:
        jar: microservices-webinars-0.0.1.jar
        jarLocation: ""
      clusterName: localpulsar
      autoAck: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: food-delivery-mesh-config
data:
  webServiceURL: http://localpulsar-broker.pulsar.svc.cluster.local:8080
  brokerServiceURL: pulsar://localpulsar-broker.pulsar.svc.cluster.local:6650
